[[section-architecture-constraints]]
== Randbedingungen

[role="arc42help"]
****
.Inhalt
Randbedingungen und Vorgaben, die ihre Freiheiten bezüglich Entwurf, Implementierung oder Ihres Entwicklungsprozesses einschränken.
Diese Randbedingungen gelten manchmal organisations- oder firmenweit über die Grenzen einzelner Systeme hinweg.

* 3 Wochen Entwicklungszeit mit Vorgabe von 4 Stunden am Tag
* Spezifischen Anfragen der Organisation über Features, die auf jeden Fall implementiert werden sollen
** Beispiel: Angepasstes übernehmen der alten Termine in eine neue Anmeldung
* Alle Features müssen zumindest partiell erfüllt sein
** Fokus auf adäquate Implementation aller Features, statt ausgereifte Implementation einzelner

.Motivation
Für eine tragfähige Architektur sollten Sie genau wissen, wo Ihre Freiheitsgrade bezüglich der Entwurfsentscheidungen liegen und wo Sie Randbedingungen beachten müssen.
Sie können Randbedingungen vielleicht noch verhandeln, zunächst sind sie aber da.

.Form
Einfache Tabellen der Randbedingungen mit Erläuterungen.
Bei Bedarf unterscheiden Sie technische, organisatorische und politische Randbedingungen oder übergreifende Konventionen (beispielsweise Programmier- oder Versionierungsrichtlinien, Dokumentations- oder Namenskonvention).
****
