[[section-technical-risks]]
== Risiken und technische Schulden

[role="arc42help"]
****
.Inhalt
Eine nach Prioritäten geordnete Liste der erkannten Architekturrisiken und/oder technischen Schulden.

* Zugriff auf Datenbank
** Unikennung und E-Mail-Adressen gespeichert (Datenschutz)
* Nachteil Layer-Architecture
** Risiko dass bei großen Menge an Daten Weiterleitung nicht so performant wie möglich ist
* An.- und Abmelden von Studenten (anmelden auch von anderen Studenten)
** Implikationen auf deren Studium
* Erlagen von GitHub-Daten eines Studenten

* Konflikt Zeit und Sicherheit


.Motivation
"Risikomanagement ist Projektmanagement für Erwachsene."
-- Tim Lister, Atlantic Systems Guild

Unter diesem Motto sollten Sie Architekturrisiken und/oder technische Schulden gezielt ermitteln, bewerten und Ihren Management-Stakeholdern (z.B. Projektleitung, Product-Owner) transparent machen.

.Form
Liste oder Tabelle von Risiken und/oder technischen Schulden, eventuell mit vorgeschlagenen Maßnahmen zur Risikovermeidung, Risikominimierung oder dem Abbau der technischen Schulden.
****

